# Generated by Django 6.0.5 on 2026-05-12 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель картриджа')),
                ('color', models.CharField(choices=[('black', 'Черный'), ('cyan', 'Голубой'), ('magenta', 'Пурпурный'), ('yellow', 'Желтый'), ('other', 'Другой')], default='black', max_length=20, verbose_name='Цвет')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_use', 'В эксплуатации'), ('empty', 'Пустой'), ('refilling', 'На заправке'), ('ready', 'Готов к установке'), ('repair', 'В ремонте'), ('writeoff', 'Списан')], default='new', max_length=20, verbose_name='Состояние')),
                ('refill_count', models.IntegerField(default=0, verbose_name='Количество заправок')),
                ('last_refill_date', models.DateField(blank=True, null=True, verbose_name='Дата последней заправки')),
                ('first_use_date', models.DateField(blank=True, null=True, verbose_name='Дата первого использования')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в базу')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': 'Картриджи',
                'ordering': ['inventory_number'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название должности')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название помещения')),
                ('building', models.CharField(blank=True, max_length=50, null=True, verbose_name='Здание/Корпус')),
                ('floor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Этаж')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'ordering': ['building', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО полностью')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_materially_responsible', models.BooleanField(default=False, verbose_name='Материально ответственное лицо')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь системы')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='CartridgeRefillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refill_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заправки')),
                ('refill_count_after', models.IntegerField(verbose_name='Количество заправок после этой')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill_history', to='core.cartridge', verbose_name='Картридж')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_refills', to='core.employee', verbose_name='Кто выполнял заправку')),
            ],
            options={
                'verbose_name': 'История заправки картриджа',
                'verbose_name_plural': 'Истории заправок картриджей',
                'ordering': ['-refill_date'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Серийный номер')),
                ('status', models.CharField(choices=[('active', 'В эксплуатации'), ('repair', 'В ремонте'), ('storage', 'На складе'), ('writeoff', 'Списан')], default='active', max_length=20, verbose_name='Состояние')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('warranty_end', models.DateField(blank=True, null=True, verbose_name='Окончание гарантии')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в базу')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_printers', to='core.employee', verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
                'ordering': ['inventory_number'],
            },
        ),
        migrations.AddField(
            model_name='cartridge',
            name='current_printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_cartridges', to='core.printer', verbose_name='Установлен в принтер'),
        ),
        migrations.CreateModel(
            name='PrinterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('printer_type', models.CharField(choices=[('laser', 'Лазерный'), ('inkjet', 'Струйный'), ('matrix', 'Матричный'), ('mfd', 'МФУ')], default='laser', max_length=50, verbose_name='Тип принтера')),
                ('cartridge_compatible', models.CharField(blank=True, max_length=100, null=True, verbose_name='Совместимый картридж')),
            ],
            options={
                'verbose_name': 'Модель принтера',
                'verbose_name_plural': 'Модели принтеров',
                'ordering': ['manufacturer', 'model_name'],
                'unique_together': {('manufacturer', 'model_name')},
            },
        ),
        migrations.AddField(
            model_name='printer',
            name='printer_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.printermodel', verbose_name='Модель принтера'),
        ),
        migrations.CreateModel(
            name='PrinterMoveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата перемещения')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина перемещения')),
                ('from_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printer_moves_from_emp', to='core.employee', verbose_name='От ответственного')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем выполнено перемещение')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_history', to='core.printer', verbose_name='Принтер')),
                ('to_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printer_moves_to_emp', to='core.employee', verbose_name='К ответственному')),
                ('from_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printer_moves_from', to='core.room', verbose_name='Из помещения')),
                ('to_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printer_moves_to', to='core.room', verbose_name='В помещение')),
            ],
            options={
                'verbose_name': 'История перемещения принтера',
                'verbose_name_plural': 'Истории перемещений принтеров',
                'ordering': ['-move_date'],
            },
        ),
        migrations.AddField(
            model_name='printer',
            name='current_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers_current', to='core.room', verbose_name='Текущее помещение'),
        ),
        migrations.CreateModel(
            name='CartridgeMoveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата перемещения')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина перемещения')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_history', to='core.cartridge', verbose_name='Картридж')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем выполнено')),
                ('from_printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartridge_moves_from', to='core.printer', verbose_name='Из принтера')),
                ('to_printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartridge_moves_to', to='core.printer', verbose_name='В принтер')),
                ('from_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartridge_moves_from_room', to='core.room', verbose_name='Со склада')),
                ('to_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartridge_moves_to_room', to='core.room', verbose_name='На склад')),
            ],
            options={
                'verbose_name': 'История перемещения картриджа',
                'verbose_name_plural': 'Истории перемещений картриджей',
                'ordering': ['-move_date'],
            },
        ),
        migrations.AddField(
            model_name='cartridge',
            name='storage_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_cartridges', to='core.room', verbose_name='Место хранения'),
        ),
    ]
